server:
    port: 8080

spring:
  application:
    name: SmartNoodles
  profiles:
    active: prod

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.108.227.151/ #jdbc:mysql://localhost:3306/dbgirl_test?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
    username: mysql
    password: mysql

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

accsess:
  bind_address: localhost
  bind_port: 8989