server:
    port: 8080

spring:
  application:
    name: SmartNoodles
  profiles:
    active: prod

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.108.218.108/smart_ruler #jdbc:mysql://localhost:3306/dbgirl_test?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
    username: root
    password: 123

  #redis:
    #host: 10.108.218.64
    #post:
    #password:
    #database:
    #pool:
      #max-idle: 8
      #min-idle: 0
      #max-active: 8
      #max-wait: -1

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

accsess:
  bind_address: localhost
  bind_port: 8989

mybatis:
  configuration:
    cache-enabled: true
    lazy-loading-enabled: false
    aggressive-lazy-loading: false
    multiple-result-sets-enabled: true
    default-executor-type: reuse
    default-statement-timeout: 25000
  type-aliases-package: org.spring.springboot.domain
