server:
    port: 8080

spring:
  application:
    name: SmartNoodles
  profiles:
    active: prod

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.108.218.108:3306/smart_ruler?characterEncoding=UTF-8   #jdbc:mysql://localhost:3306/dbgirl_test?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
    username: root
    password: 123
    #name: smart_ruler

  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto:create-drop


mybatis:
  configuration:
    cache-enabled: true
    lazy-loading-enabled: false
    aggressive-lazy-loading: false
    multiple-result-sets-enabled: true
    default-executor-type: reuse
    default-statement-timeout: 25000
  type-aliases-package: org.tjlcast.server.domain




